"use client";

import { FormEvent, useState } from "react";
import { Check, Pencil, Plus, Trash2 } from "lucide-react";
import { Product } from "@/lib/types";
import { useStore } from "@/components/store";

const categories: Product["category"][] = ["Playing Cues", "Break Cues", "Jump Cues", "Custom Cues", "Cue Cases", "Accessories"];
export default function StudioPage() {
  const { settings, saveSettings, customProducts, saveProduct, deleteProduct } = useStore();
  const [notice, setNotice] = useState("");
  const editProduct = (product: Product) => {
    const name = window.prompt("Название товара", product.name);
    if (!name?.trim()) return;
    const price = window.prompt("Цена в USD", String(product.price));
    const stock = window.prompt("Количество в наличии", String(product.stock));
    if (price === null || stock === null || Number.isNaN(Number(price)) || Number.isNaN(Number(stock))) return;
    saveProduct({ ...product, name: name.trim(), price: Number(price), stock: Number(stock) });
    setNotice("Товар изменён.");
  };
  const settingsSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const d = new FormData(event.currentTarget); saveSettings({ email: String(d.get("email")), phone: String(d.get("phone")), telegram: String(d.get("telegram")), instagram: String(d.get("instagram")), city: String(d.get("city")), courierFee: Number(d.get("courierFee")), freeDeliveryFrom: Number(d.get("freeDeliveryFrom")) }); setNotice("Настройки сохранены на этом устройстве."); };
  const productSubmit = (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const d = new FormData(event.currentTarget); const name = String(d.get("name")).trim(); const category = String(d.get("category")) as Product["category"]; const material = String(d.get("material")).trim(); saveProduct({ id: Date.now(), slug: `${name.toLowerCase().replace(/[^a-z0-9а-я]+/gi, "-")}-${Date.now().toString().slice(-4)}`, name, category, price: Number(d.get("price")), shortDescription: `${material} · ${category}`, description: String(d.get("description")), images: [{ sheet: category.includes("Cues") ? "light" : "accessories", position: 0, caption: "Общий вид" }], material, shaft: category.includes("Cues") ? "Maple" : "—", tipDiameter: category.includes("Cues") ? "12.4 mm" : "—", weight: category.includes("Cues") ? "18–20 oz" : "—", length: category.includes("Cues") ? '58"' : "—", joint: category.includes("Cues") ? "Radial" : "—", tip: category.includes("Cues") ? "Medium" : "—", stock: Number(d.get("stock")), collection: "Studio", new: true }); event.currentTarget.reset(); setNotice("Товар добавлен в каталог на этом устройстве."); };
  return <section className="studio-page"><div className="checkout-heading"><p className="eyebrow">Локальная панель владельца</p><h1 className="page-title">Настройки студии.</h1><p>Данные хранятся только в браузере этого устройства — удобно для личного проекта без сервера.</p></div>{notice && <p className="studio-notice" role="status"><Check size={17}/>{notice}</p>}<div className="studio-grid"><form className="checkout-form" onSubmit={settingsSubmit}><fieldset><legend>Контакты и доставка</legend><label>Почта<input name="email" type="email" defaultValue={settings.email}/></label><label>Телефон<input name="phone" defaultValue={settings.phone}/></label><label>Telegram<input name="telegram" defaultValue={settings.telegram} placeholder="https://t.me/..."/></label><label>Instagram<input name="instagram" defaultValue={settings.instagram} placeholder="https://instagram.com/..."/></label><label>Город самовывоза<input name="city" defaultValue={settings.city}/></label><label>Доставка, USD<input name="courierFee" type="number" min="0" defaultValue={settings.courierFee}/></label><label>Бесплатная доставка от, USD<input name="freeDeliveryFrom" type="number" min="0" defaultValue={settings.freeDeliveryFrom}/></label></fieldset><button className="button button-dark">Сохранить настройки</button></form><form className="checkout-form" onSubmit={productSubmit}><fieldset><legend>Добавить товар</legend><label>Название<input required name="name"/></label><label>Категория<select name="category">{categories.map((category) => <option key={category}>{category}</option>)}</select></label><label>Материал<input required name="material" placeholder="Например, Hard Maple"/></label><label>Цена, USD<input required name="price" type="number" min="1"/></label><label>В наличии<input required name="stock" type="number" min="0" defaultValue="1"/></label><label>Описание<textarea required name="description" rows={3}/></label></fieldset><button className="button button-dark"><Plus size={18}/>Добавить товар</button></form></div><section className="studio-products"><p className="eyebrow">Добавленные товары</p>{customProducts.length ? customProducts.map((product) => <article key={product.id}><div><b>{product.name}</b><span>{product.stock} шт. · ${product.price}</span></div><button type="button" onClick={() => editProduct(product)} aria-label={`Изменить ${product.name}`}><Pencil size={18}/>Изменить</button><button type="button" onClick={() => deleteProduct(product.id)} aria-label={`Удалить ${product.name}`}><Trash2 size={18}/>Удалить</button></article>) : <p>Пока нет товаров, добавленных через панель.</p>}</section></section>;
}
